steps:
  # - name: gcr.io/cloud-builders/git
  #   args: ['submodule', 'update', '--init', '--recursive']
  # - name: gcr.io/cloud-builders/docker
  #   entrypoint: '/bin/bash'
  #   args:
  #     - '-c'
  #     - |-
  #       set -e

  #       echo "Building the website using a makefile..."
  #       make build BUILD_CONFIGS=_config.yml,_config_stage.yml
  - name: gcr.io/cloud-builders/npm
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        set -e
        npm install -g firebase-tools

        echo "Deploying website to a staging channel on firebase..."
        FIREBASE_DEPLOY_RESPONSE=$(firebase hosting:channel:deploy --expires 7d pr$_PR_NUMBER-$_HEAD_BRANCH --project=$PROJECT_ID)
        echo $$FIREBASE_DEPLOY_RESPONSE | grep -Eo "https://drewroen-sandbox--[a-zA-Z0-9./?=_%:-]*" > FIREBASE_STAGING_URL

        echo "Deployed website to $(cat FIREBASE_STAGING_URL)"
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        set -e

        echo "Installing github cli (using instructions from https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt)..."
        apt update && apt install -y \
        curl \
        gpg
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg;
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null;
        apt update && apt install -y gh;

        echo "Logging into github under bot account..."
        echo $$GH_PAT_TOKEN > token
        gh auth login --with-token < token

        echo "Commenting staging url on PR..."
        PR_BODY=\
        "Visit the preview URL for this PR (updated for commit $COMMIT_SHA):

        $(cat FIREBASE_STAGING_URL)"

        gh pr comment $_PR_NUMBER --edit-last --body "$$PR_BODY" --repo $REPO_FULL_NAME || \
          gh pr comment $_PR_NUMBER --body "$$PR_BODY" --repo $REPO_FULL_NAME
    secretEnv: ['GH_PAT_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/drewroen-sandbox/secrets/gh_token_comment/versions/latest
    env: 'GH_PAT_TOKEN'
timeout: 1200s
logsBucket: gs://github_staging_logs
options:
  logging: GCS_ONLY
