# Provide instructions for google Cloud Build to build and upload the flutter
# dashboard docker image to artifact registry.

steps:
  - name: gcr.io/$PROJECT_ID/firebase
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        firebase hosting:channel:deploy --expires 7d pr$_PR_NUMBER-$_HEAD_BRANCH --project=$PROJECT_ID
        firebase hosting:channel:list --json > firebase_channels.json
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        echo "Installing jq using apt..."
        apt update && apt install -y jq

        echo "Obtaining staging url from hosting channel list"
        STAGING_URL=$$(cat firebase_channels.json | jq '.result.channels[]|select(.url|contains("https://$PROJECT_ID--pr$_PR_NUMBER-$_HEAD_BRANCH")) | .url' -r)
        echo "Obtained staging url: $$STAGING_URL"

        echo "Installing gh cli..."
        apt update && apt install -y \
        curl \
        gpg
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg;
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null;
        apt update && apt install -y gh;

        echo "Logging into github under bot account..."
        echo $$GH_PAT_TOKEN > token
        gh auth login --with-token < token

        echo "Commenting staging url on PR..."

        PR_BODY=\
        "Visit the preview URL for this PR (updated for commit $COMMIT_SHA):

        $$STAGING_URL"

        gh pr comment $_PR_NUMBER --edit-last --body "$$PR_BODY" --repo drewroengoogle/test-script || \
          gh pr comment $_PR_NUMBER --body "$$PR_BODY" --repo drewroengoogle/test-script
    secretEnv: ['GH_PAT_TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/drewroen-sandbox/secrets/gh_token_comment/versions/latest
    env: 'GH_PAT_TOKEN'
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
logsBucket: gs://drewroen-sandbox_cloudbuild/source
