steps:
  # - name: gcr.io/cloud-builders/git
  #   args: ['submodule', 'update', '--init', '--recursive']
  # - name: gcr.io/cloud-builders/docker
  #   entrypoint: '/bin/bash'
  #   args:
  #     - '-c'
  #     - |-
  #       set -e

  #       echo "Building the website using a makefile..."
  #       make build BUILD_CONFIGS=_config.yml,_config_stage.yml
  - name: gcr.io/$PROJECT_ID/firebase
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        set -e
        echo "Deploying website to a staging channel on firebase..."
        FIREBASE_DEPLOY_RESPONSE=$(firebase hosting:channel:deploy --expires 7d pr$_PR_NUMBER-$_HEAD_BRANCH --project=$PROJECT_ID)
        echo $$FIREBASE_DEPLOY_RESPONSE | grep -Eo "https://drewroen-sandbox--[a-zA-Z0-9./?=_%:-]*" > FIREBASE_STAGING_URL

        echo "Deployed website to $(cat FIREBASE_STAGING_URL)"
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args: ['cloud_build/scripts/comment_url_on_pr.sh']
    secretEnv: ['GH_PAT_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/drewroen-sandbox/secrets/gh_token_comment/versions/latest
    env: 'GH_PAT_TOKEN'
timeout: 1200s
logsBucket: gs://github_staging_logs
options:
  logging: GCS_ONLY
  automapSubstitutions: true
